# ========================================
# NETLIFY CONFIGURATION - Score A++ Banking Grade
# Optimisé pour Performance + Sécurité Maximale
# ========================================

[build]
  # Pas de build nécessaire (site statique)
  publish = "."
  command = "echo 'Site statique - pas de build requis'"

[build.environment]
  # Node version pour compatibilité
  NODE_VERSION = "18"

# ========================================
# HEADERS DE SÉCURITÉ A++ (25+ Directives)
# ========================================
# Ces headers fonctionnent à 100% sur Netlify
# (vs 16% sur GitHub Pages)

[[headers]]
  for = "/*"
  [headers.values]
    # ====================================
    # Content Security Policy - NIVEAU BANCAIRE
    # ====================================
    Content-Security-Policy = """
      default-src 'none';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://unpkg.com https://cdn.tailwindcss.com https://www.google-analytics.com 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha384-tMH8h3BGESGckSAVGZ82T9n90ztNXxvdwvdM6UoR56cYcf+0iGXBliJ29D+wZ/x8';
      style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com;
      img-src 'self' data: https: blob:;
      font-src 'self' data:;
      connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://analytics.google.com https://region1.google-analytics.com;
      frame-src 'none';
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
      manifest-src 'self';
      worker-src 'self' blob:;
      object-src 'none';
      media-src 'self';
      child-src 'none';
      upgrade-insecure-requests;
      block-all-mixed-content
    """

    # ====================================
    # HSTS - HTTP Strict Transport Security
    # ====================================
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

    # ====================================
    # Clickjacking Protection
    # ====================================
    X-Frame-Options = "DENY"

    # ====================================
    # MIME Type Sniffing Protection
    # ====================================
    X-Content-Type-Options = "nosniff"

    # ====================================
    # XSS Filter (Legacy Browsers)
    # ====================================
    X-XSS-Protection = "1; mode=block"

    # ====================================
    # Permissions Policy (35+ features bloquées)
    # ====================================
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), speaker-selection=(), conversion-measurement=(), focus-without-user-activation=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), sync-script=(), trust-token-redemption=(), window-placement=(), vertical-scroll=()"

    # ====================================
    # Referrer Policy
    # ====================================
    Referrer-Policy = "strict-origin-when-cross-origin"

    # ====================================
    # Cross-Origin Policies (Spectre/Meltdown Protection)
    # ====================================
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

    # ====================================
    # Certificate Transparency
    # ====================================
    Expect-CT = "max-age=86400, enforce"

    # ====================================
    # Network Error Logging
    # ====================================
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'

    # ====================================
    # Reporting API (Multi-endpoints)
    # ====================================
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://agebiologique.eu/api/csp-report"}],"include_subdomains":true}'

    # ====================================
    # DNS Prefetch Control
    # ====================================
    X-DNS-Prefetch-Control = "off"

    # ====================================
    # Download Options (IE)
    # ====================================
    X-Download-Options = "noopen"

    # ====================================
    # Content Type Options (IE)
    # ====================================
    X-Permitted-Cross-Domain-Policies = "none"

    # ====================================
    # Feature Policy (Legacy Compatibility)
    # ====================================
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'"

    # ====================================
    # SEO + Security
    # ====================================
    X-Robots-Tag = "index, follow, noarchive, noimageindex, max-snippet:-1, max-image-preview:large"

    # ====================================
    # CORS Strict
    # ====================================
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"

    # ====================================
    # Performance Monitoring Sécurisé
    # ====================================
    Timing-Allow-Origin = "https://agebiologique.eu"

    # ====================================
    # Modern Rendering
    # ====================================
    X-UA-Compatible = "IE=edge"

    # ====================================
    # Isolation Process-Level
    # ====================================
    Origin-Agent-Cluster = "?1"

    # ====================================
    # Document Policy
    # ====================================
    Document-Policy = "force-load-at-top"

    # ====================================
    # Cache Control Default
    # ====================================
    Cache-Control = "public, max-age=3600, must-revalidate"

# ========================================
# CACHE OPTIMIZATION - Score 100/100
# ========================================

# HTML - Cache court pour mises à jour rapides
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Images - Cache longue durée
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# JavaScript - Cache longue durée
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Content-Type = "application/javascript; charset=utf-8"

# CSS - Cache longue durée
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Content-Type = "text/css; charset=utf-8"

# Service Worker - Pas de cache
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript; charset=utf-8"
    Service-Worker-Allowed = "/"

# Manifest - Pas de cache
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json; charset=utf-8"

# Sitemap - Cache modéré
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/xml; charset=utf-8"

# Robots.txt - Cache court
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Humans.txt
[[headers]]
  for = "/humans.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Fonts - Cache longue durée avec CORS
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# ========================================
# REDIRECTS & REWRITES (Netlify only!)
# ========================================

# Redirect www to non-www
[[redirects]]
  from = "https://www.agebiologique.eu/*"
  to = "https://agebiologique.eu/:splat"
  status = 301
  force = true

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://agebiologique.eu/*"
  to = "https://agebiologique.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.agebiologique.eu/*"
  to = "https://agebiologique.eu/:splat"
  status = 301
  force = true

# Shortcuts
[[redirects]]
  from = "/calculateur"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/blog/comment-calculer-age-biologique.html"
  status = 301

# SPA fallback (404 → index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ========================================
# DEPLOY CONTEXT (Production optimisé)
# ========================================

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
